language: go
go:
- 1.15.x

deploy:
  provider: releases
  api_key:
    secure: nMOD3Zqecv/QDX9HLDjlWlFLCDvaubyNyFSyMOFJDGDiSyRYOyrB4b/Udj3pbFuIe5q3RzHupuyk3IWV5Sp9rokyGxRJ3ALA/O0GDhv+u1yxXmQMUezMVg1EdUCvQ8VC90iEVt5wxRg8UvIjsu4WatkaNAn4r6f/0eCUZGgMrQbOEWG5UA4VW/GtPMHXTFEp14EAwWhGP2ZoNsMBwHEncO/5RK4caUB4sgtot9nojTbWoQAvKA5TbWzpjOZGURcltzmx590pi7e/8x8MhtTiHgWmFu0XHjPdGlnyQdlQuy609frrZ/IzlUVB+OpTR8irPB0m6+bM33YYOc1DvIvBsWAm6EGcmYV9GCIykewyU9tkkpS6JaURhc4GjZfmOqaG9xoy8pDvWlthWTV/eX5AjNdFx/YMVrUZOle3/SarRvypRoPaUhcqtvWmxAstYyF4/9G2Fdc8dDBk2dsRRlQ3TfRF2v1XuUvPi1Fvbo84JfSgVSVzg7yCupP3Gva4vjsc1JUSZpaNBkdQdxdm9vnFb6ajKXERaWf+hwlDwEakmyBYQE43h8T0Q7IwQz4o1r4IqMhicRqLG4ZPgNJROH0nGc/FatN66RxJFfwg/dan0bItHedUKnBwnm5Ea5b6LFxUNMRBBr9NXyy4Kb4XjrUuhPJ29FPqJZ8XUlq9p/EsThI=
  file: bin/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: stefan-kiss/getbin
    tags: true

